### ISSUE TITLE
Make it easier for people to contact Sandstorm

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm-website#103]
Some options:
- perhaps an e-mail icon visible on the nav bar
- an obvious "email Sandstorm/us" link or button
- links to individual emails in the team section
- contact form

**Comment by neynah** [comment]
Resolved by new redesign. :D
- almost have a contact button on each page
- contact link in the footer as well

**Comment by paulproteus** [comment]
+1
