### ISSUE TITLE
"Authentic apps" heading on features page has unrelated image

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm-website#128]
At https://sandstorm.io/features the heading about authentic apps, where you can see who created the package with verified PGP signature and stuff... shows a picture of the auto-update drop down. This seems like a disconnect, since nothing about that image shows the verified author stuff, which might be better represented by a shot of the author block on an app.

**Comment by neynah** [comment]
@ocdtrekkie Wow! I have no idea how I missed this. Will fix it now.

**Comment by ocdtrekkie** [comment]
Fixed by #135
