### ISSUE TITLE
Inconsistent apps count

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm-website#141]
https://sandstorm.io/features - "48 apps and growing"
https://oasis.sandstorm.io/ - "over 50 apps available"

:(

**Comment by kentonv** [comment]
Yeah, /features actually fetches the current number whereas the Oasis splash was written optimistically. Maybe we should make it fetch the number dynamically too?

**Comment by ocdtrekkie** [comment]
Quick, someone port two apps so the splash is not wrong! :P

**Comment by kentonv** [comment]
Quick Survey brings us to 49. Just need one more.

(Even though it would take 10 seconds to fix the text to match reality, I like feeling the pressure to fix reality to match the text...)

**Comment by ocdtrekkie** [comment]
Both now just say "over 50 apps available", and we now have over 50 apps.

**Comment by kentonv** [comment]
Yet another example of an ignored problem fixing itself.
