### ISSUE TITLE
update app market screenshot

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm-website#148]
The current screenshot of the App Market on the frontpage looks like this (the old app market with the sidebar):

![image](https://cloud.githubusercontent.com/assets/1584904/12573896/49b44f68-c3b3-11e5-9e8f-42068b0c1eeb.png)

It should probably reflect reality.

**Comment by neynah** [comment]
Closed with #161

**Comment by kentonv** [comment]
@neynah BTW if you write "Closes #161" or "Fixes #161" inside a commit's or pull request's description, then when it is merged the bug will automatically be closed.
