### ISSUE TITLE
On /apps/ , use the demo as the default click target

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm-website#15]
Right now, on https://sandstorm.io/apps/ , the `button` tags use an `onclick` parameter to a Javascript function.

It'd be nice to change that in the following ways:

* Use a HREF, rather than a complicated Javascript thing

* Have the HREF, by default, start the app in the demo.

Rationale:

* This way, people can click the "Try it" button on showing up to https://sandstorm.io/apps/ and it'll actually do something.

* Fans of ported apps like MediaGoblin can right-click copy-location and get a URL they can pass around to random people they meet who they wish to expose to their awesome project.

Implementation notes:

* This requires storing the `appId` (the public key of the author) in the page in a machine-readable format. To get the `appId` you might have to download & unzip the SPK and pull it out of the manifest.

* This requires changing the Javascript to read the `appId` from this machine-readable format, such as a `data-app-id` attribute, see also https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes

* This requires changing the Javascript so the instance chooser at the top of the page causes all the HREFs to change. (Arguably the button text should change from "Try it" to "Install" when you choose something other than the demo. Or maybe the button text should always be "Install".)

**Comment by neynah** [comment]
@paulproteus should we close this issue now?

**Comment by kentonv** [comment]
Indeed, this is way old. Plus I think we actually resolved it at the time. :)
