### ISSUE TITLE
Decide on text changes to make the website frontpage explain what Sandstorm is useful for, to end-users

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm-website#200]
Purpose of this issue:

This issue is closed when Kenton is completely satisfied with the text changes for the website to accommodate the new focus on explaining what Sandstorm is.

Probably what will happen is:

- @neynah will submit a pull request with 80%-OK text.
- @kentonv will leave comments on that PR.
- Once that's done, we'll close this issue.

**Comment by paulproteus** [comment]
Argh, hit submit too soon. I'm still editing. I'll update this comment when I'm done editing.

**Comment by paulproteus** [comment]
OK - @neynah I believe this captures the tasks from the meeting. I've assigned to you for now.

I believe the process we decided on was:

- You own all these tasks, including proposing new copy.
- Once you have a pull request or mockup image uploaded somewhere, Kenton will review that and give feedback.
- Once any feedback is addressed, Kenton will merge & deploy & update website.

Preferably this can be done this week since Kenton is on vacation next week. I don't decide when you do things, though, so I'll leave the specifics of when it gets done to be a judgment call between you/Jade/Kenton.

**Comment by ocdtrekkie** [comment]
As a note on this topic: Any chance that before Kenton goes on vacation, the Sandstorm community can get a quick brief on this stuff? The Meeting Notes have hinted at the shift to a "productivity suite" thing I think for two weeks, and while this PR helps provide some insight, I still feel like we may be a little in the dark on exactly where the change in focus lies. It'd be easier to provide feedback and suggestions on these sorts of PRs with that information as well.

**Comment by paulproteus** [comment]
Good point @ocdtrekkie . I'll aim to email sandstorm-dev within a day or two with an overview.

**Comment by neynah** [comment]
> I don't know what "emphasize demo itself" or "productivity suite + other apps" or graphic for productivity suite" meant in the notes. Is there an action item that came from any of those notes?

Emphasize productivity suite but also make link to app market (other apps) accessible.

**Comment by ocdtrekkie** [comment]
It's a new week, so I just wanted to remind you here @paulproteus on this convo.

**Comment by paulproteus** [comment]
Archiving old description; removing checkboxes

This issue captures action items from the @jadeqwang @kentonv @neynah @paulproteus meeting yesterday on the topic of how to adjust the website to talk about a "productivity suite".

(I'm writing this list based on @neynah 's notes from the meeting; therefore @neynah if I missed something, please let me know and/or edit this issue. I'm moving it to GitHub issues for the benefit of having an issue that people can subscribe to and improved task-tracking clarity compared to an etherpad.)

Specific action items:

### On homepage

- Change the top header from "Sandstorm is an open source operating system for personal and private clouds." to something like "Sandstorm: a self-hostable web productivity suite"

- Change the other above-the-fold header from "What can I do with it?" to something like "Online productivity apps under your control"

- Replace the "Try any app right now: Visit the App Market" call to action area with a call to action area that contains a demo button and a link to "Get Sandstorm" (the same two calls to action that are above-the-fold)

- Replace the area that says ("Create" "Collaborate" "Communicate") with screenshots & brief descriptions of four apps on Sandstorm, presumably Wekan, Rocket.Chat, Etherpad, and Davros. The screenshots should be more legible; some ways to achieve that include making the screenshots full-width, and/or increasing their resolution, and/or screenshotting just a small fraction of the app that successfully indicates what the app is without showing the entire app.

- security section: have the two mini-sections be about "security" and "compliance" - remove audit log quasi-screenshot, and mention auditing in the compliance text; have the compliance text emphasize the benefits of self-hosting for compliance. Remove the phrase "buggy apps" and replace it with something a little more optimistic.

- usability section: focus on integration; perhaps show grain list, perhaps show a link to the app market to emphasize the Sandstorm ecosystem

- Generally review all three of Usability, Security, Freedom sections to make sure they make sense with the "productivity suite" text change; adjust as needed. Consider making them less wordy.

### On /get ("Get Sandstorm")

- Adjust "Self-host" to be visually above "Managed hosting"

### Other notes

- I don't know what "emphasize demo itself" or "productivity suite + other apps" or graphic for productivity suite" meant in the notes. Is there an action item that came from any of those notes?
- I've moved "self-host first, managed hosting second" to be part of https://github.com/sandstorm-io/sandstorm-website/issues/201
- I've moved "guided tour won't show up to tell you to install an app" to https://github.com/sandstorm-io/sandstorm/issues/2242
- I've moved "feature key page needs more description" to https://github.com/sandstorm-io/sandstorm-website/issues/201
- I've moved "install page (send this page to colleague) -> IT landing page" to https://github.com/sandstorm-io/sandstorm-website/issues/201

**Comment by zarvox** [comment]
Closing per @neynah's request
