### ISSUE TITLE
Create graphics for each of the apps in the productivity suite

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm-website#205]
This issue can be closed when there's a successful PR that adds the graphics to the area of the page describing Wekan, Rocket.Chat, Davros, & Etherpad into the `productivity-suite` branch.

**Comment by neynah** [comment]
Proposed copy so far. Each app will need it's own screenshot so we should think of some reasonable scenarios to be displayed/communicated in each one:

**Chat**
Sync up with your colleagues securely with Rocket.Chat.
[Rocket.Chat screenshot]

**File Storage**
Store all your files in the cloud and share them with others with Davros.
[Davros screenshot]

**Task & Project Management**
Organize all your tasks and ideas with Wekan.
[Wekan screenshot]

**Document Editing**
Create, edit, and collaborate on documents with Etherpad.
[Etherpad screenshot]

**Comment by neynah** [comment]
Here are concepts Asheesh & I came up with so far for theming the screenshots. Seeking feedback from @jadeqwang & @kentonv on which theme we should choose / suggestion for another theme/scenario.

**Option A: Primary-school math education**
Rocket.Chat

<tonda> how were your students today?
<evan> mostly great. The third graders are really :100: - they know what they're doing this year :)
<evan> The second graders had real trouble with colors for some reason
<tonda> yeah, I found colors really hard to teach too (<-- add a :) reaction)

Etherpad
Title: Assessment ideas
Different ways to assess arithmetic for kindergarten students

Ask students to tell me a story involving numbers
Think about common household objects: ask them visualize numbers of green and purple grapes and talk about the total number
Write 4 and 5 down, then tell me which is greater

Things to remember when teaching

Always be concrete - don't talk about the number 4, talk about having 4 of something

Reference: http://www2.carrollk12.org/Assets/file/ElemMath/CountyBenchmarks/JBMY/JB.K.Calendar.2016.pdf

Davros

- Upload a few things from https://www.google.com/search?q=creative%20commons%20licensed%20kindergarten into a Davros grain that seem related to Kindergarten. Mostly PDFs but maybe some images and Word documents.

Wekan

Column: To do
- Decide week 5 homework
- Organize parent-teacher meeting starting 11/1
Column: Doing
- Decide week 4 homework
- Ask Sophie for help planning week 5
Column: Done
- Decide week 3 homework
- Grade week 3 homework
- Decide week 2 homework
- Grade week 2 homework
- Call Jamarico's parents to congratulate on great scores



**Option B: Architecture/interior design firm**

Rocket.Chat
- discuss materials/

Etherpad
Project overview/plan (partner, architect, intern)

Davros
Project files:
- drafts
- design specifications
- contract

Wekan
Tasks/ideas
- Concepts
- To do's
- Completed
- Documents to sign



**Option C: Event planning (convention/trade show)**

Rocket.Chat
- discuss event branding/design

Etherpad
Draft for vendor agreement

Davros
- sponsor folder
- vendor folder
- contracts folder
- event branding 

Wekan
Tasks/ideas
- Confirmed vendors
- Sponsors
- Possible venues
- Shopping list
- Contracts to prepare

**Comment by kentonv** [comment]
These are neat examples, but it might also make sense to look at our actual early customers. Maybe a university example would make sense?

**Comment by neynah** [comment]
Yeah, I'll take the responsibility of tweaking Option A more towards a University scenario then.

**Comment by zarvox** [comment]
Closing per @neynah's request
