### ISSUE TITLE
The blog should probably have an RSS feed

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm-website#214]
So, as a static-published website, this isn't inherent, and would likely require manual maintenance, but... there's no RSS feed for the blog, which is really odd.

One could suggest there is a mailing list sign up on the right, but things that end up on the blog don't end up on the mailing list. Technically I am notified of every blog post anyways, but that's only because I'm the sort of hyper-attentive nerd who is subscribed to the sandstorm-website repo, which I assume is abnormal. ;)

**Comment by zarvox** [comment]
https://sandstorm.io/feed.xml should be an Atom feed.  We specify

```
<link rel="alternate" type="application/rss+xml" title="Sandstorm.io Blog" href="/feed.xml">
```

in the <head> of https://sandstorm.io/news/ .  Is this failing to trigger whatever you use to detect feeds?

**Comment by ocdtrekkie** [comment]
I don't try and detect feeds, I generally look for an RSS or feed link on the page. I honestly didn't know you could embed an RSS feed in a link rel tag.

**Comment by zarvox** [comment]
If you use Firefox, "Bookmarks -> Subscribe to this page" does feed-detection.

Most feed-reading software can be handed an arbitrary URL and will sniff out the feed link within.  But it probably wouldn't hurt to have a feed in the collection of links in the sitemap at the bottom of the page?

**Comment by ocdtrekkie** [comment]
I use TTRSS on Sandstorm for my feeds, so I've never really looked at feed detection as a thing.

**Comment by kpreid** [comment]
> https://sandstorm.io/feed.xml should be an Atom feed. 

No, it isn't. It's RSS. You should be actually using Atom! It's way less broken.

Also, have some lint: http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fsandstorm.io%2Ffeed.xml
