### ISSUE TITLE
Unclear what a grain is

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm-website#217]
We display how many grains comes with each option of Sandstorm on https://sandstorm.io/get, however, we don't provide any information as to what a grain is to aide decision making. 

I think it's worth adding a footnote or linking to text somewhere else(perhaps docs) to explain what a grain is.

**Comment by malsony** [comment]
@neynah According to https://sandstorm.io/get#oasis-pricing:

A grain is a document, chat room, mail box, notebook, blog, or anything else you create. A 5-grain limit applies to accounts on the Free plan.

I take the term "grain" a "grain of sand".

**Comment by kentonv** [comment]
Yes, it looks like Nena fixed this but forgot to close the bug.
