### ISSUE TITLE
On /business , mention priority support

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm-website#222]
Steps to reproduce:
- As a prospective customer who is using Sandstorm Standard just fine,
- Go to https://sandstorm.io/business and see if there is anything they want to pay for,
- Notice that there's only mention of features, not support,
- Therefore skip purchasing Sandstorm.

Expected behavior:
- https://sandstorm.io/business lists all of the things that Sandstorm for Work includes, including Priority Support.

@neynah @kentonv @JamborJan  curious for your thoughts!

**Comment by neynah** [comment]
Priority support is definitely a value-add so +1. We should communicate that. What are the specifics of priority support? E.g. what turnaround to we promise, can they reach us through channels inaccessible to those with non-priority support?

**Comment by ocdtrekkie** [comment]
It is already hilariously easy to get in touch with Sandstorm team members!

As an IT person though, without respect specifically for Sandstorm, I particularly care about:

- When can I get a hold of you? What if this cannot be fixed during regular business hours?
- How fast will this be resolved? How much of this fix will you do for me? (Remote sessions are wonderful.)

**Comment by JamborJan** [comment]
In some cases I agree with @ocdtrekkie, it is easy to get in touch with you guys and I guess it's also quite easy to scale this up in case you get more users and customers.

When it comes to the question "why should I pay?" from my point of view it is support but not in terms of basic Sandstorm operation but rather in specific projects where I want to achieve something with Sandstorm. For example I'm blocked with a small project here: https://github.com/sandstorm-io/sandstorm/issues/1648. In the current situation I perfectly understand that other tasks have a higher priority for Sandstorm. In case of payed support I would expect that such things are going quicker and more efficient. On the feature lost for Sandstorm for Work there is no point which convinces me to pay as I don't need a single one of those at the moment. But this is very specific to my use case.

To come back to the question: yes priority Support could be mentioned, but maybe with some examples what exactly that means. I would not be satisfied if simple tasks and questions are answered quick and more detailed questions and help on my project are excluded.

I hope that helps.

**Comment by kentonv** [comment]
@JamborJan FWIW, we would be very happy to negotiate contracts in which we implement some feature by some date and get paid some amount. Perhaps we should mention this on our web site. I think Rocket.Chat's site has something like this.

Unfortunately, though, the standard Sandstorm for Work subscription fee is not enough to pay for us to redirect large chunks of developer time unless the subscriber has a very large number of users. So, we probably can't lump this in with SfW features.

**Comment by zenhack** [comment]
We can probably close this; sandstorm is no longer a business, and no longer has any kind of paid support offering.
