### ISSUE TITLE
Adjust Oasis splash page to say "productivity suite"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm-website#228]
(using this project since @neynah doesn't have access to the "prod" repo, and as far as I know, there's no git repo for the Oasis splash page anyway)

@neynah see below screenshots. Requesting your +1/-1 on the phrasing.

Once we have your +1/-1 I will request that Kenton make the change.

**Before** is on the right. **After** is on the left.

![screenshot from 2016-09-13 19 17 17](https://cloud.githubusercontent.com/assets/25457/18497911/22f4374a-79e7-11e6-9897-fbaa0f30af84.png)

raw diff, for Kenton's convenience in the future.

```
diff --git a/index.html b/index.html
index 2456c49..70d357b 100644
--- a/index.html
+++ b/index.html
@@ -12,6 +12,8 @@
 
 <p>Install apps with one click to chat, store files, collaboratively edit documents, and more. <a href="https://apps.sandstorm.io">Over 50 apps available</a> – or upload your own!</p>
 
+<p>Sandstorm is a self-hostable web productivity suite. This site &mdash; Sandstorm Oasis &mdash; is our hosted offering, with plans starting at $0/month.</p>
+
 <p><a title="Demo Rocket.Chat" class="demo" href="https://oasis.sandstorm.io/appdemo/vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0"><img src="rocketchat.jpg" alt="Demo Rocket.Chat" /></a> <a title="Demo Wekan" class="demo" href="https://oasis.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"><img src="wekan.jpg" alt="Demo Wekan" /></a> <a title="Demo EtherCalc" class="demo" href="https://oasis.sandstorm.io/appdemo/a0n6hwm32zjsrzes8gnjg734dh6jwt7x83xdgytspe761pe2asw0"><img src="ethercalc.jpg" alt="Demo EtherCalc" /></a></p>
 
 <p>Oasis is run by <a href="https://sandstorm.io">Sandstorm.io</a>. Rather use your own server? Sandstorm is Open Source: <a href="https://sandstorm.io/install/">Run your own »</a></p>
```

**Comment by paulproteus** [comment]
Assigning to @neynah for her +1/-1/feedback.

**Comment by neynah** [comment]
Sorry if this is a pain but I think a lot of copy on this page needs to change in general.

>"Install apps with one click..."

I think we should instead communicate that on Oasis people can just easily go ahead and use the apps and collaborate rather than saying they can install the apps. Using apps is more compelling than installing them even if installing is a required action.

>"Over 50 apps available-or upload your own."

Should update this to "Over 60 apps available". I also think pitching "upload your own" as a value-add is a little misleading since it requires a lot of effort to upload your own app. I think we should emphasize that people can package their own apps but the right place to do this is on the App Market, Website, and GitHub repo rather than Oasis.

>"This site - Sandstorm Oasis - is our hosted offering, with plans starting at $0/month"

Calling Oasis a site sort of breaks the illusion/experience of this being a place to collaborate and use apps. I also think there's some unnecessary repetition here since at the bottom of the page it already says "Oasis is run by Sandstorm.io"

>"Oasis is run by Sandstorm.io"

This kind of makes us sound like a third party.

I'm confident that you can come up with good revisions but I thought I'd also propose something if it makes it easier for you:

"Sandstorm is a self-hostable web productivity suite. Collaborate with others using apps for chatting, file storage, document editing, task management, and more. Start for free and access all of our 60+ apps.

Sandstorm Oasis is hosted by the Sandstorm Team. Sandstorm is Open Source; you can host it own your own server."

**Comment by paulproteus** [comment]
I agree with the above - it generally needs work. I thought I'd make a laserlike small change for now, but I'm OK diving into the above.

**Comment by paulproteus** [comment]
I've taken the liberty of making a few copy edits to your proposed text @neynah . Here's a fresh screenshot of before & after.

**Before** on left. **After** on right.

![screenshot from 2016-09-14 17 05 17](https://cloud.githubusercontent.com/assets/25457/18534190/8686314e-7a9d-11e6-8339-cfad209999ba.png)

Output of git diff:

```
paulproteus@slittingmill:~/projects/oasis-splash-page$ git diff
diff --git a/index.html b/index.html
index 2456c49..c2c308c 100644
--- a/index.html
+++ b/index.html
@@ -10,13 +10,12 @@
 <div id="main">
 <h1 id="welcome-to-sandstorm-oasis">Welcome to Sandstorm Oasis</h1>
 
-<p>Install apps with one click to chat, store files, collaboratively edit documents, and more. <a href="https://apps.sandstorm.io">Over 50 apps available</a> – or upload your own!</p>
+<p>Sandstorm is a self-hostable web productivity suite. Collaborate with others using apps for chatting, file storage, document editing, task management, and more. Start for free and access all of our <a href="https://apps.sandstorm.io/">60+ apps.</a></p>
 
 <p><a title="Demo Rocket.Chat" class="demo" href="https://oasis.sandstorm.io/appdemo/vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0"><img src="rocketchat.jpg" alt="Demo Rocket.Chat" /></a> <a title="Demo Wekan" class="demo" href="https://oasis.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"><img src="wekan.jpg" alt="Demo Wekan" /></a> <a title="Demo EtherCalc" class="demo" href="https://oasis.sandstorm.io/appdemo/a0n6hwm32zjsrzes8gnjg734dh6jwt7x83xdgytspe761pe2asw0"><img src="ethercalc.jpg" alt="Demo EtherCalc" /></a></p>
 
-<p>Oasis is run by <a href="https://sandstorm.io">Sandstorm.io</a>. Rather use your own server? Sandstorm is Open Source: <a href="https://sandstorm.io/install/">Run your own »</a></p>
+<p>Sandstorm Oasis is hosted by the <a href="https://sandstorm.io/">Sandstorm</a> team. Sandstorm is open source; you can <a href="https://sandstorm.io/install/">host it on your own server.</a></p>
 
 </div>
 </body>
 </html>
-

```

Re-requesting review/+1/-1 from @neynah

**Comment by paulproteus** [comment]
FWIW I'm wondering if I should make the second-paragraph's "Sandstorm team" not contain a link, and then make the "Sandstorm" in "Sandstorm is open source" be the link to sandstorm.io.

**Comment by neynah** [comment]
>FWIW I'm wondering if I should make the second-paragraph's "Sandstorm team" not contain a link, and then make the "Sandstorm" in "Sandstorm is open source" be the link to sandstorm.io.

Yeah let's do that instead.

The copy I proposed is a bit longer than I thought but I think I'm still +1 on it. :)

**Comment by paulproteus** [comment]
New screenshots.

Before on left; after on right.

![screenshot from 2016-09-14 18 15 01](https://cloud.githubusercontent.com/assets/25457/18535238/397921b8-7aa7-11e6-93c8-cbdc36f887bd.png)

New git diff:

```
paulproteus@slittingmill:~/projects/oasis-splash-page$ git diff
diff --git a/index.html b/index.html
index 2456c49..578a760 100644
--- a/index.html
+++ b/index.html
@@ -10,13 +10,12 @@
 <div id="main">
 <h1 id="welcome-to-sandstorm-oasis">Welcome to Sandstorm Oasis</h1>
 
-<p>Install apps with one click to chat, store files, collaboratively edit documents, and more. <a href="https://apps.sandstorm.io">Over 50 apps available</a> – or upload your own!</p>
+<p>Sandstorm is a self-hostable web productivity suite. Collaborate with others using apps for chatting, file storage, document editing, task management, and more. Start for free and access all of our <a href="https://apps.sandstorm.io/">60+ apps.</a></p>
 
 <p><a title="Demo Rocket.Chat" class="demo" href="https://oasis.sandstorm.io/appdemo/vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0"><img src="rocketchat.jpg" alt="Demo Rocket.Chat" /></a> <a title="Demo Wekan" class="demo" href="https://oasis.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"><img src="wekan.jpg" alt="Demo Wekan" /></a> <a title="Demo EtherCalc" class="demo" href="https://oasis.sandstorm.io/appdemo/a0n6hwm32zjsrzes8gnjg734dh6jwt7x83xdgytspe761pe2asw0"><img src="ethercalc.jpg" alt="Demo EtherCalc" /></a></p>
 
-<p>Oasis is run by <a href="https://sandstorm.io">Sandstorm.io</a>. Rather use your own server? Sandstorm is Open Source: <a href="https://sandstorm.io/install/">Run your own »</a></p>
+<p>Sandstorm Oasis is hosted by the Sandstorm team. <a href="https://sandstorm.io/">Sandstorm</a> is open source; you can <a href="https://sandstorm.io/install/">host it on your own server.</a></p>
 
 </div>
 </body>
 </html>
-
```

**Comment by paulproteus** [comment]
Re-requesting review/+1/-1 from @neynah :)

**Comment by neynah** [comment]
+1!

**Comment by paulproteus** [comment]
@kentonv requesting your review/merge/deploy. `git diff` is above; let me know if you need it in a different format.

**Comment by neynah** [comment]
On second thought, does saying "hosted by the Sandstorm Team" make it sound less-serious of a service? 

If so, maybe instead of:

>"Sandstorm Oasis is hosted by the Sandstorm team"

We want to say:

"Sandstorm Oasis is hosted by Sandstorm."

Or:

"Oasis is hosted by Sandstorm."

@paulproteus I'll leave it up to you if you want to make this additional change.

**Comment by paulproteus** [comment]
@neynah I'm happy enough with the original text:

> Oasis is run by <a href="https://sandstorm.io">Sandstorm.io</a>.

It has the following advantages:

- Already Kenton-approved

- It says "is run by" which I think is clearer than "is managed by." The latter ("managed") makes it sound to me like the Sandstorm software automatically manages it, and therefore anyone who gets the Sandstorm software can get the same experience, which isn't accurate.

However, I don't know what about the "hosted" makes it sound less serious to you. Perhaps if you can elaborate on that, then I'll understand better where you're coming from.

If I don't get an answer by 4:45pm, I'll ask Kenton at 4:45pm to apply the patch you said "+1" to, so that we have something out there. I'm OK with further discussion and further changes, but I want to make sure we don't let the perfect be the enemy of the good.

**Comment by neynah** [comment]
Let's just go with it. +1!

**Comment by paulproteus** [comment]
@neynah these changes are live, and furthermore I now have access to change the Oasis splash page directly! I'll close this issue for now. If you have other suggested changes, I'm cool discussing them too. Since I have access to the actual Oasis splash page Hacker CMS grain, I'm tentatively +1 on A/B testing string changes here in case that interests you later on.
