### ISSUE TITLE
Demo should be more visible

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm-website#245]
From user testing it seems that users would prefer to try out a demo of Sandstorm before purchasing or creating an account. We should make the demo more visible and accessible. We currently only have 2 links on the home page.

I think we should also add the demo as a:
- footer link
- button/link on /get

**Comment by ocdtrekkie** [comment]
I am going to close this one. We do have a link on /get, and I think the focus on getting people into the demo is lessened by the lack of a SaaS offering.
