### ISSUE TITLE
Write blog post announcing "privileged" sandbox

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm-website#249]
https://github.com/sandstorm-io/sandstorm/pull/2644 makes Sandstorm compatible with many, many more Linux distributions, so it'd be smart to write a blog post about it, and probably make sense to send that to the announcements email list.

**Comment by ocdtrekkie** [comment]
The biggest question I still have about this new mode is "which is better for me?" It was noted that even new distros of Ubuntu and such may end up using the new mode on a new install. So I have to wonder which is more secure, what are the associated risks with each, and if I have a Linux distro that can support either, which should I prefer?

Do you expect the userns-based method to eventually still be dominant, as newer distros come out with support for it, or is this new method eventually going to be the main one?

**Comment by paulproteus** [comment]
This one will be the primary one we use, I believe.

We can make sure to speak to the security trade-offs as part of https://github.com/sandstorm-io/sandstorm/issues/2645 :)

**Comment by kentonv** [comment]
@ocdtrekkie The trade-offs are incredibly minor, so honestly the answer for you as a user is: You want whichever one works. If both work, it doesn't matter which you use. Hopefully, users never have to even know that there are two sandbox modes, much less choose between them.

**Comment by zarvox** [comment]
Fixed in #258.
