### ISSUE TITLE
Compatibility issue with blog feed

### ISSUE THREAD

**Issue by kpreid** [sandstorm-io/sandstorm-website#284]
As interpreted by NetNewsWire 4 for Mac, https://sandstorm.io/feed.xml contains no entries. Unfortunately, I could not extract any information about why.

(Though feed validators say that it is encoded as UTF-8 but not declared as such in the Content-Type.)

How 'bout you switch to Atom? :)

**Comment by kentonv** [comment]
It would appear that it _is_ Atom, or at least the first line seems to declare it as such, though it also declares itself as RSS and I never understood the difference.

FWIW the template that  generates it is here:

https://github.com/sandstorm-io/sandstorm-website/blob/master/feed.xml

Patches welcome. :)

**Comment by kpreid** [comment]
It's not Atom. It's RSS with some pieces (the `atom:link`) borrowed from Atom. This can be seen just from the XML with little understanding of the specifications.

    <rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">

`xmlns:atom=...` means that _if_ an element or attribute name begins with `atom:` then it is from the Atom namespace. (`xmlns:foo="bar"`, by itself, means nothing whatsoever; it just declares a name prefix, an "import statement" if you will.) The root `rss` element is in no namespace (which is normal for RSS). Contrast with Wikipedia's example of an Atom feed,

    <feed xmlns="http://www.w3.org/2005/Atom">

where `xmlns` (no colon) is used, meaning that all following elements (with no colons) are implicitly in the Atom namespace. (This could be equivalently written as `<atom:feed xmlns:atom="...">`.)

(Ahem. Sorry, bit of a rant there. I am of the opinion that XML is under-appreciated due to the backlash from it being massively overused in some areas.)

Your patches-welcome is noted.

**Comment by kpreid** [comment]
—it just started working. Either you did something (I assume not) or my (closed-source...) client software had a quirk. Oh well! Sorry for the bother!
