### ISSUE TITLE
Subscribing to mailing list seems to fail

### ISSUE THREAD

**Issue by hamoid** [sandstorm-io/sandstorm-website#296]
I fill the form
![2018-07-14-101354_344x220_scrot](https://user-images.githubusercontent.com/108264/42722606-0eb21942-874f-11e8-8f0b-9ad208cd09e0.png)

and I get this nice image:
![2018-07-14-101320_415x504_scrot](https://user-images.githubusercontent.com/108264/42722607-10e7cf5e-874f-11e8-8681-0aaf9d673534.png)

Not sure if subscribing worked or not...

**Comment by ocdtrekkie** [comment]
Random guess: The mailing list may not be active anymore. It hasn't been used in a long time. Your best bet to be notified right now about Sandstorm news is likely subscribing to the sandstorm-dev mailing list: https://groups.google.com/forum/#!forum/sandstorm-dev and following https://sandstorm.io/news/ in an RSS reader.

**Comment by hamoid** [comment]
Cool. Maybe it's good to replace the box with a link or something, to not confuse people :)

**Comment by kentonv** [comment]
Oh yeah I shut it down because they were charging us like $150/mo just to store the list which we were never mailing... Forgot that there was a signup form on the web site.

**Comment by kentonv** [comment]
I've removed all the mailchimp signup forms I could find. Thanks for the report.
