### ISSUE TITLE
Sandstorm webpage: “This recording has been archived”

### ISSUE THREAD

**Issue by LemmingAvalanche** [sandstorm-io/sandstorm-website#316]
https://sandstorm.io/install :

![image](https://user-images.githubusercontent.com/2229597/73743589-36775480-474f-11ea-9699-ea24a5520022.png)

**Comment by ocdtrekkie** [comment]
This is a duplicate of #309, and a PR to fix it, #307, is already open.

Little bit of web bitrot, sorry about that! Thanks for reporting it though.
