### ISSUE TITLE
Remove references to educational use case

### ISSUE THREAD

**Issue by CaptainCalliope** [sandstorm-io/sandstorm-website#318]
[This page](https://sandstorm.io/go/education) and references to it need to be removed from the website. I see a link to it in the bottom navigation. Not sure if there are other references to it elsewhere.

**Comment by ocdtrekkie** [comment]
Are we thinking Sandstorm isn't good for educators?

**Comment by zenhack** [comment]
Relevant IRC discussion: https://freenode.irclog.whitequark.org/sandstorm/2020-03-12#26562057

I'm not actually big on the idea of outright removing it, but I think we feel the page is a bit to market-y. I'd *prefer* to tweak the presentation so it sounds less like a mature supported product. But I also don't personally have a lot of motivation to do the work on it, and @kentonv said he felt similarly. If someone wants to take on updating the presentation, I think that would be better.

**Comment by ocdtrekkie** [comment]
@zenhack Ah, I am much on board with removing overly forward thinking website terms. I recall the business page talking about auditing features and the like that aren't likely to exist soon.

But I definitely think we need to communicate how Sandstorm is ideal for different environments.

**Comment by zenhack** [comment]
So I'm looking back at this, and there's actually nothing on that page that isn't already implemented as far as I can tell (unlike /business) -- what do we think is actually misleading about this? What would need to change for it to feel right?

**Comment by ocdtrekkie** [comment]
Personally, I like this page. I'd love to see a "classroom app" (I kinda wrote a concept document for one, at one point) to really provide for the use case, but I think Sandstorm is useful to educational institutions (and is used by some educational institutions) already.

**Comment by zenhack** [comment]
I'd be fine with just closing this issue.

Quoting Jacob Weisz (2020-09-05 00:32:09)
