### ISSUE TITLE
Unblock Kiwi IRC Users

### ISSUE THREAD

**Issue by indolering** [sandstorm-io/sandstorm-website#319]
You link to Kiwi IRC on the website, but there is a bot kicking out users with an unregistered nick (which also kicks out Matrix bridge users, btw).

You should probably fix this (by switching to Matrix 😸).

**Comment by zenhack** [comment]
Yeah, we've talked about reverting the registration requirement but haven't actually settled on doing so. Originally @kentonv added it because we were seeing a lot of spam. I'd be in favor of giving it a try for a bit without the restriction, but ultimately he has to make the call.

**Comment by ocdtrekkie** [comment]
As a note, you *can* use the Matrix bridge, it's just a bit of a pain to get set up and registered on IRC. I recently switched to using Matrix for #sandstorm myself. @zenhack and others are on Matrix as well.

**Comment by zenhack** [comment]
Indeed, and there's a room alias `#sandstorm:matrix.org` that points at it. I'm tempted to say we should also link to that on the website, but it probably doesn't make sense if users are just going to get kicked.

**Comment by zenhack** [comment]
I think the moderation policy is back to default now that we've moved to #sandstorm on libera.chat, and I'm inclined to keep it that way unless there's an actual problem. So I think we can close this.
