### ISSUE TITLE
Sidebar Widget on Blog

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm-website#7]
We need a sidebar widget on the blog with:
- sign up for announcement list
- links to social (twitter, fb, github)
- try the demo button
- pre-order button

That widget should also be in the demo. ^_^

**Comment by kentonv** [comment]
@jadeqwang You're getting Nena to design this, right?

**Comment by jadeqwang** [comment]
yep

**Comment by paulproteus** [comment]
I think this has shipped! @kentonv would you be willing to close this?
